### ISSUE TITLE
Crash when talking to one of the Know-It-All Brothers

### ISSUE THREAD

**Issue by balsh** [Rinnegatamante/Shipwright#3]
There is a crash when talking to one of the Know-It-All Brothers in their house at the start of the game in Kokiri village. It happens when you ask him for the map tutorial. It should be available from most save files I guess (I play with the game in french)

Their house is circled in red here
![Image](https://github.com/user-attachments/assets/4e1012b7-df36-49b0-8fee-5b2414cafe9c)

**Comment by 0lorak** [comment]
In my case, the game does not crash. I am playing in English. Thus, maybe is something related to language. 
By the way, the game plays beautifully on my PS Vita 1000, congratulations to @Rinnegatamante for this amazing job! :clap:

**Comment by Rinnegatamante** [comment]
Were you playing a Master Quest or normal rom?

**Comment by balsh** [comment]
> Were you playing a Master Quest or normal rom?

This is using the recommended debug rom no-MQ in french

**Comment by 0lorak** [comment]
> Were you playing a Master Quest or normal rom?

I am playing in English the same debug GC rom as @balsh.

**Comment by Rinnegatamante** [comment]
![Image](https://github.com/user-attachments/assets/9ace8622-bae3-495d-85cb-f115da7053b1) 
Fixed, will be available in the next update.

**Comment by Rinnegatamante** [comment]
Fixed in v.1.1

**Comment by balsh** [comment]
Thank you for the update but it still crashes for me on 1.1 idk why
Not a big deal, I just hope there is not other crashes like this later on.
